timezone: Asia/Bangkok
future: false
permalink: /posts/:categories/:title
markdown: rdiscount
highlighter: pygments
title: prashanta
tagline: just a blog
gauges_id: 503c5af6613f5d0f19000027
url: http://prashanta.github.io/
paginate: 12
