timezone: Asia/Bangkok
future: false
markdown: rdiscount
highlighter: pygments
title: code/signal
tagline: just a blog
gauges_id: 503c5af6613f5d0f19000027
url: http://prashanta.github.io/
paginate: 10
paginate_path: "/blog/page:num/"
