auto: true
server: true
permalink: /posts/:categories/:title
pygments: true
future: false
path: http://cs.prashanta.me
title: code/signal
tagline: experiments, magic blue smoke, bugs
gauges_id: 503c5af6613f5d0f19000027